"""
Erzeuge eine Animation einer Bahnhofsuhr
"""

from pytamaro.de import (
    Grafik, Farbe,
    weiss, schwarz, rot, rgb_farbe, transparent,
    ellipse, rechteck, leere_grafik,
    ueberlagere, kombiniere, fixiere, drehe,
    zeige_grafik
)

NENNDURCHMESSER = 600

RING_AUSSEN_RADIUS = NENNDURCHMESSER * 0.51

# Abmessungen gemäss Originalskizzen:
# https://www.eguide.ch/en/objekt/sbb-bahnhofsuhr/

RING_INNEN_RADIUS = NENNDURCHMESSER * 0.5
STRICH_AUSSEN_RADIUS = NENNDURCHMESSER * 0.485

MINUTEN_STRICH_LAENGE = NENNDURCHMESSER * 0.035
MINUTEN_STRICH_BREITE = NENNDURCHMESSER * 0.014

STUNDEN_STRICH_LAENGE = NENNDURCHMESSER * 0.12
STUNDEN_STRICH_BREITE = NENNDURCHMESSER * 0.035

MINUTEN_ZEIGER_KURZE_LAENGE = NENNDURCHMESSER * 0.12
MINUTEN_ZEIGER_LANGE_LAENGE = NENNDURCHMESSER * 0.46
MINUTEN_ZEIGER_BREITE = NENNDURCHMESSER * (0.052 + 0.036) / 2

STUNDEN_ZEIGER_KURZE_LAENGE = NENNDURCHMESSER * 0.12
STUNDEN_ZEIGER_LANGE_LAENGE = NENNDURCHMESSER * 0.32
STUNDEN_ZEIGER_BREITE = NENNDURCHMESSER * (0.064 + 0.052) / 2

SEKUNDEN_ZEIGER_KURZE_LAENGE = NENNDURCHMESSER * 0.165
SEKUNDEN_ZEIGER_LANGE_LAENGE = NENNDURCHMESSER * 0.312
SEKUNDEN_ZEIGER_SCHEIBE_DURCHMESSER = NENNDURCHMESSER * 0.105
SEKUNDEN_ZEIGER_BREITE = NENNDURCHMESSER * 0.014


def hintergrund() -> Grafik:
    pass # TODO
